//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtiruz.Model2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokunka
    {
        public int Number_chet { get; set; }
        public string Stoimost { get; set; }
        public string Srok_postavki { get; set; }
        public string kol_vo_tovar { get; set; }
        public Nullable<int> Code_tovar { get; set; }
        public Nullable<int> Postavchik { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Postavchik2 Postavchik2 { get; set; }
    }
}
